### ISSUE TITLE
Shouldn't provider be wrapped around another class?

### ISSUE THREAD

**Issue by rlam3** [jkyeo/RxMoyaMapperDemo#1]
Shouldn't provider be wrapped around another class or be some sort of singleton to be a safer design? 

Also, what how would you recommend on designing the provider with JWT/Oauth authentication ?

**Comment by jkyeo** [comment]
@rlam3 Considering using the mapper in rx-chain. So I design it as Observer extension function。Well, it can also define as static function.
About JWT/Oauth authentication, maybe I will focus on it someday.

**Comment by rlam3** [comment]
@jkyeo when you talk about rx-chain, what do you mean? 

From what I understand you are just extending the functionality of Observable and mapping your results into structs/models. 

If you were to use static function, how would it be different from what you are doing it now? 

Thanks!

**Comment by jkyeo** [comment]
@rlam3 I mean that I define the map function as an extension of Observable and in this way we can call the map function like this way:

``` swift
netProvider.request(NetService.someFunc())
            .mapResponseToObj(SomeModel.self)
            .subscribe(
                onNext: { mode in
                    // do something here
                },
                onError: { error in
                    // handle error here
                }
            )
            .addDisposableTo(disposeBag)
```

But if define it as static function, the map operation may happen in onNext closure:

``` swift
netProvider.request(NetService.someFunc())
            .subscribe(
                onNext: { response in
                    // do something after map here
                   let model = Mapper.mapResponseToObj(SomeModel.self)
                },
                onError: { error in
                    // handle error here
                }
            )
            .addDisposableTo(disposeBag)
```

Hope I have explained it
